<?php
/**
 * THE IMPORT PLAN. GENERATED BY .claude/import/build-plan.php. DO NOT EDIT.
 *
 * Mark's list is the structure. Descriptions and schedules come from what
 * Mark supplied, then from the Stonewall Project sheet, then from the
 * export's most recent occurrence. Each event records which, in 'from'.
 */
return array (
  'generated' => '2026-09-03 17:52:18 UTC',
  'horizon' => '2026-12-31',
  'organizers' => 
  array (
    'Elizabeth Taylor 50-Plus Network' => 
    array (
      0 => 'The Elizabeth Taylor 50-Plus Network for Gay, Bi & Trans Men',
      1 => 'Elizabeth Taylor 50-Plus Network for Gay, Bi & Trans Men',
      2 => 'The Elizabeth Taylor 50-Plus Network',
      3 => '50-Plus Network',
    ),
    'Aging Services' => 
    array (
    ),
    'Programa Latino' => 
    array (
    ),
    'TransLife' => 
    array (
    ),
    'Black Brothers Esteem' => 
    array (
      0 => 'Black Brothers Esteem (BBE)',
      1 => 'BBE',
    ),
    'HUES' => 
    array (
      0 => 'Healing & Uniting Every Sista (HUES)',
      1 => 'Healing and Uniting Every Sista (HUES)',
      2 => 'Healing & Uniting Every Sista',
    ),
    'Stonewall Project' => 
    array (
      0 => 'The Stonewall Project',
    ),
    'PWUD Health' => 
    array (
    ),
    'Onyx Northwest' => 
    array (
    ),
  ),
  'venues' => 
  array (
    'SFAF Main Office' => 
    array (
      'street' => '940 Howard Street',
      'city' => 'San Francisco',
      'state' => 'CA',
      'zip' => '94103',
    ),
    'Strut' => 
    array (
      'street' => '470 Castro St',
      'city' => 'San Francisco',
      'state' => 'CA',
      'zip' => '94114',
    ),
  ),
  'series' => 
  array (
    0 => 
    array (
      'name' => 'Coffee Social',
      'organizer' => 'Elizabeth Taylor 50-Plus Network',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Coffee Social',
          'source' => 'Community Coffee Social (Elizabeth Taylor 50-Plus Network)',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
            0 => '2026-09-05',
            1 => '2026-09-12',
            2 => '2026-09-26',
          ),
          'start' => '10:00',
          'end' => '12:00',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'Join us at our Saturday Morning Coffee Social at the famous Maxfield\'s House of Caffeine, where Wendy and her friendly staff invite us to have a drink and a bite and spend time with other community members. It is a great way to start the weekend!',
        ),
        1 => 
        array (
          'title' => 'Coffee On Us',
          'source' => '',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
            0 => '2026-09-19',
          ),
          'start' => '10:00',
          'end' => '12:00',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'Join us at our Saturday Morning Coffee Social at the famous Maxfield\'s House of Caffeine, where Wendy and her friendly staff invite us to have a drink and a bite and spend time with other community members. It is a great way to start the weekend!',
        ),
      ),
    ),
    1 => 
    array (
      'name' => 'Dinner with Friends Community Meal',
      'organizer' => 'Elizabeth Taylor 50-Plus Network',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Dinner with Friends Community Meal',
          'source' => 'Dinner with Friends',
          'from' => 'export',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '17:00',
          'end' => '20:00',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/programs/50Plus-Salsa-Sunday-9-scaled.jpg',
          'content' => 'Join the Elizabeth Taylor 50-Plus Network for a community meal on the last Wednesday of the month. The 50-Plus Network is a social support network for gay, bisexual, and trans men age 50 and older, inclusive of people who are HIV-negative and living with HIV.

<span data-teams="true">We provide a nutritious meal, and we sit together to enjoy great conversation, camaraderie, and celebrate birthdays for the month.  Join us! </span>

<span data-teams="true"><strong>For details and to RSVP,</strong> contact Paul at  (415)-728-3116 or paguilar@sfaf.org or Vince at (415) 706- 4963 or vcrisostomo@sfaf.org. Please leave your name and number if you call.</span>

&nbsp;

&nbsp;',
        ),
      ),
    ),
    2 => 
    array (
      'name' => 'Damn, Daddy!',
      'organizer' => 'Elizabeth Taylor 50-Plus Network',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Damn, Daddy!',
          'source' => 'Damn, Daddy! - Support Group (Online)',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => 'weekly:1:3',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '13:30',
          'end' => '15:30',
          'venue' => '',
          'online' => true,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/programs/Damn-Daddy.jpg',
          'content' => '"Damn, Daddy!" is a drop-in peer support group hosted by Aging Services at the San Francisco AIDS Foundation designed specifically for gay, bisexual, and transgender men aged 50 and older. The group provides a sex-positive and confidential space to discuss real-talk topics related to aging with dignity and pride, including sex, health, relationships, drugs, and family dynamics.',
        ),
      ),
    ),
    3 => 
    array (
      'name' => 'Virtual Check-In',
      'organizer' => 'Elizabeth Taylor 50-Plus Network',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Virtual Check-In',
          'source' => '50-Plus Wednesday Night Virtual Check-in (Members Only) - Elizabeth Taylor 50-Plus Network',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => 'weekly:1:3',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '18:00',
          'end' => '19:30',
          'venue' => '',
          'online' => true,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'Join us over Zoom as we check in with each other from the comfort of our own homes. Sometimes there is a topic of discussion, and sometimes it is a check-in to see how everyone is doing. Stay connected, and also find out what is happening in and around SFAF.',
        ),
      ),
    ),
    4 => 
    array (
      'name' => 'Game Night',
      'organizer' => 'Elizabeth Taylor 50-Plus Network',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Game Night',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    5 => 
    array (
      'name' => 'Transformaciones',
      'organizer' => 'Aging Services',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Transformaciones',
          'source' => 'Transformaciones',
          'from' => 'export',
          'case' => 'rule',
          'pattern' => 'monthly_nth:1:3',
          'also' => 
          array (
            0 => 
            array (
              0 => 3,
              1 => 3,
            ),
          ),
          'on' => 
          array (
          ),
          'start' => '15:00',
          'end' => '17:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/events/Transformaciones-Apr2026_calendar.png',
          'content' => 'Grupo de Apoyo para TGNCI (Transgénero, Género No Conforme, No Binario e Intersex) Latine inmigrantes

EL GRUPO SE FACILITA EN ESPAÑOL Con Dr. Silvia Sandoval

El 1er y 3er Miércoles
3:00 a 5:00pm
940 Howard St.
Se servira una comida

Para más información: <a href="mailto:istaiti@sfaf.org">istaiti@sfaf.org</a> | 415-738-3544

Made possible through funding by ViiV Healthcare, Gilead Sciences, and Elizabeth Taylor AIDS Foundation',
        ),
      ),
    ),
    6 => 
    array (
      'name' => 'Glitter \'n Go',
      'organizer' => 'Aging Services',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Glitter \'n Go',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    7 => 
    array (
      'name' => 'Beyond the Binary',
      'organizer' => 'Aging Services',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Beyond the Binary',
          'source' => 'Beyond the Binary',
          'from' => 'export',
          'case' => 'rule',
          'pattern' => 'monthly_nth:3:1',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '14:30',
          'end' => '16:30',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/communities/trans-non-binary.jpg',
          'content' => '<p class="elementtoproof"><span style="font-size: 14.0pt; font-family: \'Times New Roman\',serif; color: black;">Beyond the Binary is a monthly event series for intersex and non-binary community of all ages to gather and enjoy a different activity together each month. </span></p>
For more information and to join the group, email Ivana at istaiti@sfaf.org.

&nbsp;

&nbsp;',
        ),
      ),
    ),
    8 => 
    array (
      'name' => 'Intergenerational TGI Brunch',
      'organizer' => 'Aging Services',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Intergenerational TGI Brunch',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    9 => 
    array (
      'name' => 'El Grupo de Apoyo Latino',
      'organizer' => 'Programa Latino',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'El Grupo de Apoyo Latino',
          'source' => 'El Grupo de Apoyo Latino',
          'from' => 'export',
          'case' => 'rule',
          'pattern' => 'weekly:1:4',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '15:00',
          'end' => '17:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/unnamed-file.pages/SFAF2020-8874-900x630-1.jpg',
          'content' => 'El Grupo de Apoyo Latino de SFAF es un grupo social y educativo que ofrece un espacio abierto, seguro, y confidencial para apoyar a la comunidad Latina afectada por el VIH y SIDA. Es un grupo diverso, donde el respeto es la base para que todos los asistentes puedan expresar libremente sus experiencias, identidad, étnicidad, nacionalidad, sexualidad, y creencias religiosas.

Todas las reuniones son en español y se llevan a cabo en un ambiente positivo, familiar, y confidencial. Ven a compartir con nosotros, estamos seguros que encontrarás apoyo y recibirás información para mejorar tu calidad de vida.

SFAF ofrece servicios a cualquier persona sin importar su situación migratoria.

Para mas información sobre El Grupo, llama al 415-632-9722.

_____

Our support group, El Grupo, has been a stable source of family and community for Latinos, Latinas and their families since the early 1980s. Join us for information about sexual health and harm reduction, meals and social support, and help finding health and social services.

Meetings are in-person at 940 Howard St Group Room A  every Thursday from 3 to 5 pm.',
        ),
      ),
    ),
    10 => 
    array (
      'name' => 'Opioid Overdose Prevention and Reversal Training',
      'organizer' => 'Programa Latino',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Opioid Overdose Prevention and Reversal Training',
          'source' => 'Capacitación sobre cómo revertir una sobredosis y cómo responder ante ella',
          'from' => 'export',
          'case' => 'rule',
          'pattern' => 'monthly_nth:3:2',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '10:00',
          'end' => '17:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Program Groups',
              1 => 'Program groups',
            ),
          ),
          'image' => '',
          'content' => '<span style="font-weight: 400;">Si usted o alguien que conoce consume drogas, es recomendable saber qué hacer en caso de una sobredosis. Proporcionamos el medicamento naloxona, que revierte la sobredosis de opioides, y capacitamos a las personas sobre qué hacer en caso de una sobredosis. </span>

<span style="font-weight: 400;">Este evento se imparte en español.</span>

<span style="font-weight: 400;">Si tiene alguna pregunta o desea unirse al grupo, comuníquese con Jorge al 415-734-8011 o envíe un correo electrónico a </span><a href="mailto:jzepeda@sfaf.org"><span style="font-weight: 400;">jzepeda@sfaf.org</span></a><span style="font-weight: 400;">.</span>

_________________________

<b>Overdose reversal &amp; response training </b>

<span style="font-weight: 400;">If you or people you know use drugs, it’s a good idea to know what to do in case of an overdose. We provide the medication naloxone which reverses opioid overdose, and train people on what to do in case of an overdose. </span>

<span style="font-weight: 400;">This event is facilitated in Spanish. </span>

<span style="font-weight: 400;">Please contact Jorge 415-734-8011 or </span><a href="mailto:jzepeda@sfaf.org"><span style="font-weight: 400;">jzepeda@sfaf.org</span></a><span style="font-weight: 400;"> with any questions or to join the group.</span>',
        ),
      ),
    ),
    11 => 
    array (
      'name' => 'Health Education & Legal Assistance Group',
      'organizer' => 'Programa Latino',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Health Education & Legal Assistance Group',
          'source' => 'Grupos de Educación sobre Salud del Programa Latino + Grupo de Asistencia Legal del Programa Latino',
          'from' => 'export',
          'case' => 'rule',
          'pattern' => 'weekly:1:2',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '15:00',
          'end' => '16:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Program Groups',
              1 => 'Program groups',
            ),
          ),
          'image' => '',
          'content' => '<span style="font-weight: 400;">Únase a nosotros para aprender sobre el VIH, la prevención, los servicios sociales y mucho más. Este grupo está abierto a todas las personas y se impartirá en español.</span>

<span style="font-weight: 400;">Para obtener más información o unirse al grupo, comuníquese con Eduardo al 415-350-3315 o envíe un correo electrónico a </span><a href="mailto:esiqueiros@sfaf.org"><span style="font-weight: 400;">esiqueiros@sfaf.org</span></a><span style="font-weight: 400;">.</span>

<b>Programa Latino Health Education Groups </b>

<span style="font-weight: 400;">Join us to learn about HIV, prevention, social services, and more. This group is open to all people and will be facilitated in Spanish.</span>

<span style="font-weight: 400;">For more information or to join the group, contact Eduardo at 415-350-3315 or </span><a href="mailto:esiqueiros@sfaf.org"><span style="font-weight: 400;">esiqueiros@sfaf.org</span></a><span style="font-weight: 400;">.</span>

<span style="font-weight: 400;">¿Busca ayuda para resolver cuestiones legales, como asuntos de inmigración y problemas relacionados con la vivienda y el alquiler? </span>

<span style="font-weight: 400;">Nos hemos asociado con el Panel de Referencia Legal en Materia de SIDA [AIDS Legal Referral Panel] y PODER para ofrecer asesoramiento sin cita previa y apoyo gratuitos a nuestros clientes y a la comunidad.</span>

<span style="font-weight: 400;">Para obtener más información o unirse al grupo, póngase en contacto con Eduardo en el 415-350-3315 o envíe un correo electrónico a </span><a href="mailto:esiqueiros@sfaf.org"><span style="font-weight: 400;">esiqueiros@sfaf.org</span></a><span style="font-weight: 400;">.</span>

__________________________________________________

<b>Programa Latino Legal Assistance Group </b>

<span style="font-weight: 400;">Looking for assistance navigating legal issues including immigration concerns and housing and rental issues? </span>

<span style="font-weight: 400;">We are partnering with AIDS Legal Referral Panel and PODER to offer drop-in advice and support for free to our clients and community. </span>

<span style="font-weight: 400;">For more information or to join the group, contact Eduardo at 415-350-3315 or </span><a href="mailto:esiqueiros@sfaf.org"><span style="font-weight: 400;">esiqueiros@sfaf.org</span></a><span style="font-weight: 400;">. </span>

&nbsp;',
        ),
      ),
    ),
    12 => 
    array (
      'name' => 'Trans Galaxy',
      'organizer' => 'TransLife',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Trans Galaxy',
          'source' => 'TransLife Galaxy Mental Health Series',
          'from' => 'export',
          'case' => 'rule',
          'pattern' => 'monthly_nth:1:3',
          'also' => 
          array (
            0 => 
            array (
              0 => 3,
              1 => 3,
            ),
          ),
          'on' => 
          array (
          ),
          'start' => '13:00',
          'end' => '15:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/events/calendar-TransLife-Galaxy-fy24.jpg',
          'content' => 'Community-based mental health facilitators share coping skills and trauma resiliency techniques that help develop life-rebuilding practices. This group is designed for transgender, gender non-conforming, non-binary, and other TGNCI+ community members.

To attend, please email astephens@sfaf.org.',
        ),
      ),
    ),
    13 => 
    array (
      'name' => 'TransLife Drop-In',
      'organizer' => 'TransLife',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'TransLife Drop-In',
          'source' => 'TransLife Drop-In',
          'from' => 'export',
          'case' => 'rule',
          'pattern' => 'weekly:1:3',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '13:00',
          'end' => '15:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'TransLife empowers and supports group members with whatever they are going through. We understand that life as a trans woman, trans man, or gender-fluid individual can be tough. Our group brings a blend of spirituality, friendship and community to give the support you need and the family you long for. Come join us.

Questions? Email Translife@sfaf.org or call 415-487-8090.

Group held at 940 Howard St.',
        ),
      ),
    ),
    14 => 
    array (
      'name' => 'Brothers Who Read',
      'organizer' => 'Black Brothers Esteem',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Brothers Who Read',
          'source' => '',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => 'weekly:1:3',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '13:30',
          'end' => '15:30',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'Join Black Brothers Esteem (BBE) for a book club group where we read and discuss books! Conversations are honest, community-minded, and rooted in a love of reading.

All are welcome and encouraged to join.

Virtual option available, contact bbe@sfaf.org for info.',
        ),
      ),
    ),
    15 => 
    array (
      'name' => 'Phoenix Rising',
      'organizer' => 'Black Brothers Esteem',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Phoenix Rising',
          'source' => '',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => 'weekly:1:3',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '16:00',
          'end' => '18:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => '',
          'content' => 'Join Black Brothers Esteem (BBE) for our weekly support group, where we build community with other members, share our concerns, discover new perspectives, and build friendships.

Our group on the last Wednesday of the month is open to all allies.',
        ),
      ),
    ),
    16 => 
    array (
      'name' => 'BBE Game & Movie Night',
      'organizer' => 'Black Brothers Esteem',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'BBE Game & Movie Night',
          'source' => '',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => 'monthly_nth:4:5',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '17:00',
          'end' => '20:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'Join Black Brothers Esteem (BBE) once a month to play board games, watch movies, and play cards with the goal of not only winning but having fun.

Our Game Night is fun and friendly for casual board gamers, but also a great place to play the heavy cardboard. We will teach you new games, or you can bring your own and teach us.',
        ),
      ),
    ),
    17 => 
    array (
      'name' => 'HUES Sista Circles',
      'organizer' => 'HUES',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'HUES Sista Circles',
          'source' => '',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => 'monthly_nth:2:6',
          'also' => 
          array (
            0 => 
            array (
              0 => 4,
              1 => 6,
            ),
          ),
          'on' => 
          array (
          ),
          'start' => '10:00',
          'end' => '12:00',
          'venue' => '',
          'online' => true,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => '',
          'content' => 'At our twice-monthly Sista Circles, women living with and affected by HIV come together for support, connection, and meaningful conversation in a space rooted in sisterhood and healing.

Contact Ebony at egordon@sfaf.org for more information or to join.',
        ),
      ),
    ),
    18 => 
    array (
      'name' => 'Soul Sessions',
      'organizer' => 'HUES',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Soul Sessions',
          'source' => 'Soul Sessions',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => 'monthly_nth:2:4',
          'also' => 
          array (
            0 => 
            array (
              0 => 4,
              1 => 4,
            ),
          ),
          'on' => 
          array (
          ),
          'start' => '16:00',
          'end' => '18:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/posts/Image-16-1.jpg',
          'content' => 'Join HUES (Healing & Uniting Every Sista) for a twice-monthly gathering for Black women. We offer a warm and welcoming space to connect, unwind, and thrive, with engaging discussion, fun games, creative crafts, and shared experiences.

We foster joy, wellness, and community connection.

Virtual option available. Contact Ebony at egordon@sfaf.org for more info or to join virtually.',
        ),
      ),
    ),
    19 => 
    array (
      'name' => 'Express Yourself',
      'organizer' => 'Stonewall Project',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Express Yourself',
          'source' => 'Express Yourself - Support Group',
          'from' => 'sheet',
          'case' => 'list',
          'pattern' => 'weekly:1:1',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '14:30',
          'end' => '16:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/Stonewall-Express-Yourself-calendar.jpg',
          'content' => 'Join us in this art therapy group and Express Yourself! All you need is an open mind and willingness to play.',
        ),
      ),
    ),
    20 => 
    array (
      'name' => 'Off Mute',
      'organizer' => 'Stonewall Project',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Off Mute',
          'source' => 'Off Mute - Support Group',
          'from' => 'sheet',
          'case' => 'list',
          'pattern' => 'weekly:1:2',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '14:30',
          'end' => '16:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/Stonewall-Off-Mute-promo-1200x800-1.png',
          'content' => 'A substance use support group focusing on sharing and reconnecting after much time apart; open to folks with all substance use goals.',
        ),
      ),
    ),
    21 => 
    array (
      'name' => 'Stay on Target',
      'organizer' => 'Stonewall Project',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Stay on Target',
          'source' => '',
          'from' => 'sheet',
          'case' => 'list',
          'pattern' => 'weekly:1:3',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '18:00',
          'end' => '19:30',
          'venue' => 'Strut',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => '',
          'content' => 'Navigating substances requires balance. This group is for those members who would like to stay clear of some substances but still enjoy others, and also for those who would like to use any substance and focus on reducing the negative consequences of their use.

Topics include goal setting, triggers, navigating relationships and sex-drug linked behavior, exploring emotions, and also nutrition, hydration, day-after recovery and general health and well-being.',
        ),
      ),
    ),
    22 => 
    array (
      'name' => 'Abstinence Support Group',
      'organizer' => 'Stonewall Project',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Abstinence Support Group',
          'source' => 'Abstinence Support Group',
          'from' => 'sheet',
          'case' => 'list',
          'pattern' => 'weekly:1:3',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '18:00',
          'end' => '19:30',
          'venue' => 'Strut',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => '',
          'content' => 'A safe space for people with abstinence goals to support one another, share knowledge, and learn skills. We help you achieve and maintain abstinence from all substances.',
        ),
      ),
    ),
    23 => 
    array (
      'name' => 'Skills and Thrills',
      'organizer' => 'Stonewall Project',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Skills and Thrills',
          'source' => '',
          'from' => 'sheet',
          'case' => 'list',
          'pattern' => 'weekly:1:4',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '18:00',
          'end' => '19:30',
          'venue' => '',
          'online' => true,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => '',
          'content' => 'Join us for a discussion on what actually works, and what does not. We will talk skills, coping, managing emotions, distress tolerance, drug linked sexual behavior, how to make a plan to meet your goals, and much more.

Take the confusion out of recovery. This group can help harm reduction veterans or newbies process where they feel stuck or challenged.',
        ),
      ),
    ),
    24 => 
    array (
      'name' => 'El Salón',
      'organizer' => 'Stonewall Project',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'El Salón',
          'source' => 'El Salón - Grupo de apoyo',
          'from' => 'sheet',
          'case' => 'list',
          'pattern' => 'weekly:1:4',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '12:30',
          'end' => '14:00',
          'venue' => 'SFAF Main Office',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/Stonewall-El-Salon-Latino-2022_1200x800.png',
          'content' => 'Reúnete con nosotros para hablar de tu relación con alcohol y drogas y como usar de manera más saludable. Este será un espacio relajado y libre de juicios para conversar acerca de varios temas que nos afectan incluyendo las relaciones personales, familia, inmigración, cultura y más.',
        ),
      ),
    ),
    25 => 
    array (
      'name' => 'PROP',
      'organizer' => 'Stonewall Project',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'PROP',
          'source' => 'PROP Contingency Management',
          'from' => 'sheet',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '13:00',
          'end' => '14:30',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Program Groups',
              1 => 'Program groups',
            ),
            1 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => '',
          'content' => 'Structured community, counseling, referrals, and support for all people interested in addressing their use of meth or cocaine. Any and all goals are supported.

PROP centers gay, bi and trans men and other men who have sex with men, and trans women.

PROP for All is open to all adults.',
        ),
        1 => 
        array (
          'title' => 'PROP for All',
          'source' => 'PROP for All - Contingency Management',
          'from' => 'sheet',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '15:00',
          'end' => '16:30',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Program Groups',
              1 => 'Program groups',
            ),
          ),
          'image' => '',
          'content' => 'Structured community, counseling, referrals, and support for all people interested in addressing their use of meth or cocaine. Any and all goals are supported.

PROP centers gay, bi and trans men and other men who have sex with men, and trans women.

PROP for All is open to all adults.',
        ),
        2 => 
        array (
          'title' => 'PROP Empowerment',
          'source' => 'PROP Empowerment Program',
          'from' => 'sheet',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '13:00',
          'end' => '14:30',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Support Groups',
              1 => 'Support groups',
            ),
          ),
          'image' => 'https://resources.sfaf.org/wp-content/uploads/events/Stonewall-PROP-Empowerment-Program-Aug2025-calendar1.png',
          'content' => 'Structured community, counseling, referrals, and support for all people interested in addressing their use of meth or cocaine. Any and all goals are supported.

PROP centers gay, bi and trans men and other men who have sex with men, and trans women.

PROP for All is open to all adults.',
        ),
        3 => 
        array (
          'title' => 'PROP at 6th Street',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    26 => 
    array (
      'name' => 'Treatment Readiness and Recovery Capital',
      'organizer' => 'PWUD Health',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Treatment Readiness and Recovery Capital',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    27 => 
    array (
      'name' => 'Mindfulness-based Relapse Prevention',
      'organizer' => 'PWUD Health',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Mindfulness-based Relapse Prevention',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    28 => 
    array (
      'name' => 'Crafts Brunch',
      'organizer' => 'PWUD Health',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Crafts Brunch',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    29 => 
    array (
      'name' => 'Art Group',
      'organizer' => 'PWUD Health',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Art Group',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    30 => 
    array (
      'name' => 'Mobile Health Sites',
      'organizer' => 'PWUD Health',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Mission District - Martin de Porres House of Hospitality',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
        1 => 
        array (
          'title' => 'Mission District - Mission Neighborhood Resource Center',
          'source' => '',
          'from' => '',
          'case' => 'none',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
          ),
          'start' => '',
          'end' => '',
          'venue' => '',
          'online' => false,
          'cats' => 
          array (
          ),
          'image' => '',
          'content' => '',
        ),
      ),
    ),
    31 => 
    array (
      'name' => 'Strut community events',
      'organizer' => 'Onyx Northwest',
      'events' => 
      array (
        0 => 
        array (
          'title' => 'Leather Lab: Safe and Fun Impact Play',
          'source' => '',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
            0 => '2026-09-05',
          ),
          'start' => '12:00',
          'end' => '14:00',
          'venue' => 'Strut',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'Free pre-Folsom education series hosted by Onyx Northwest! The Safe and Fun Impact Play event will be hosted by Master Hines. Held at Strut, 470 Castro St., with testing and PrEP enrollment, food, and raffle prizes. This event is sponsored by Gilead and held in partnership with SFAF.',
        ),
        1 => 
        array (
          'title' => 'Leather Lab: Harm Reduction & Chemsex',
          'source' => '',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
            0 => '2026-09-12',
          ),
          'start' => '12:00',
          'end' => '14:00',
          'venue' => 'Strut',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'Free pre-Folsom education series hosted by Onyx Northwest! The Harm Reduction & Chemsex event will be hosted by Daddius ONYX. Held at Strut, 470 Castro St., with testing and PrEP enrollment, food, and raffle prizes. This event is sponsored by Gilead and held in partnership with SFAF.',
        ),
        2 => 
        array (
          'title' => 'Leather Lab: Kink and Spirituality',
          'source' => '',
          'from' => 'mark',
          'case' => 'list',
          'pattern' => '',
          'also' => 
          array (
          ),
          'on' => 
          array (
            0 => '2026-09-19',
          ),
          'start' => '12:00',
          'end' => '14:00',
          'venue' => 'Strut',
          'online' => false,
          'cats' => 
          array (
            0 => 
            array (
              0 => 'Community events',
              1 => 'Community Events',
              2 => 'Community event',
            ),
          ),
          'image' => '',
          'content' => 'Free pre-Folsom education series hosted by Onyx Northwest! The Kink and Spirituality event will be hosted by Sir Dion ONYX. Held at Strut, 470 Castro St., with testing and PrEP enrollment, food, and raffle prizes. This event is sponsored by Gilead and held in partnership with SFAF.',
        ),
      ),
    ),
  ),
);
