<?php
/**
 * Multi-site API server.
 *
 * ===========================================================================
 * DORMANT. NOT DEAD. DO NOT DELETE THIS IN A CLEANUP.
 * ===========================================================================
 *
 * UNUSED AS OF AUGUST 14, 2026, AND RETAINED DELIBERATELY. No satellite site is
 * pulling from this feed and none is planned. SFAF's other sites are on Teal
 * Media's managed platform, which is why nothing needs it today.
 *
 * IT IS KEPT FOR THE CASE THAT ENDS. If SFAF ever moves off that managed
 * platform, this is how the other sites get the calendar, and rebuilding it
 * costs far more than the clutter of keeping it. It is self-contained, it sits
 * behind its own route, and it harms nothing while it sits there:
 *
 *   the feed          GET sfaf-calendar/v1/events, registered in the main
 *                     plugin file. NOT the route the embed uses, which is
 *                     SFAF_Embed::REST_ROUTE. Deleting or breaking one cannot
 *                     affect the other.
 *   the payload       event_payload() below, the only thing that builds it.
 *   the key           multisite_api_key, generated by ajax_generate_key() from
 *                     Events > Settings > Multisite.
 *
 * IT IS SWITCHED OFF, NOT MERELY IDLE, and that is a 3.28.0 change worth
 * knowing about before turning it back on. sfaf_rest_events_permission() used
 * to treat "no key configured" as OPEN. It now treats it as CLOSED, so the feed
 * answers nobody until somebody generates a key on purpose. Any key stored
 * during earlier setup was cleared once by sfaf_retire_satellite_key(), so an
 * old credential pasted into a satellite that no longer exists is worthless.
 *
 * TO TURN IT BACK ON: generate a key on Events > Settings > Multisite and paste
 * it into each satellite. That is the whole of it; nothing else here is
 * conditional on anything.
 *
 * The main site does NOT pull from or push to anywhere. Satellites pull from
 * it, using the SFAF Calendar Satellite plugin.
 */
if ( ! defined( 'ABSPATH' ) ) exit;

class SFAF_Sync {

    public function register() {
        add_action( 'wp_ajax_uc_generate_key', array( $this, 'ajax_generate_key' ) );
    }

    /**
     * Generate + store a 32-char API key (AJAX, no page reload).
     */
    public function ajax_generate_key() {
        check_ajax_referer( 'uc_admin_nonce', 'nonce' );
        if ( ! current_user_can( 'manage_options' ) ) {
            wp_send_json_error( array( 'message' => 'Denied' ), 403 );
        }
        $key = wp_generate_password( 32, false );

        // The key lives in the dedicated credential store, not in uc_settings —
        // that option is rebuilt wholesale on every settings save, which is how
        // credentials kept going missing. See class-sfaf-credentials.php.
        SFAF_Credentials::set( 'multisite_api_key', $key );

        wp_send_json_success( array( 'key' => $key ) );
    }

    /**
     * Full event payload for the REST GET /events endpoint (consumed by
     * satellite sites). Includes every field a satellite needs to display the
     * event identically.
     */
    public function event_to_array( $post_id ) {
        $post = get_post( $post_id );

        // Category names + colour map.
        $cat_terms = wp_get_post_terms( $post_id, 'uc_event_category' );
        $categories = array();
        $cat_colors = array();
        if ( ! is_wp_error( $cat_terms ) ) {
            foreach ( $cat_terms as $t ) {
                $categories[] = $t->name;
                $color = get_term_meta( $t->term_id, '_uc_category_color', true );
                if ( $color ) {
                    $cat_colors[ $t->name ] = $color;
                }
            }
        }

        return array(
            'id'              => $post_id,
            'source_id'       => (int) ( get_post_meta( $post_id, '_uc_source_id', true ) ?: $post_id ),
            'source_site'     => get_post_meta( $post_id, '_uc_source_site', true ) ?: home_url(),
            'title'           => $post->post_title,
            'slug'            => $post->post_name,
            'content'         => $post->post_content,
            'excerpt'         => $post->post_excerpt,
            'status'          => $post->post_status,
            'date'            => get_post_meta( $post_id, '_uc_event_date', true ),
            'start_time'      => get_post_meta( $post_id, '_uc_start_time', true ),
            'end_time'        => get_post_meta( $post_id, '_uc_end_time', true ),
            'location'        => sfaf_event_location( $post_id ),
            'recurrence'      => SFAF_Recurrence::pattern_of( $post_id ),
            'capacity'        => get_post_meta( $post_id, '_uc_capacity', true ),
            'rsvp_enabled'    => get_post_meta( $post_id, '_uc_rsvp_enabled', true ),
            'gofundme_url'    => get_post_meta( $post_id, '_uc_gofundme_url', true ),
            'gofundme_goal'   => get_post_meta( $post_id, '_uc_gofundme_goal', true ),
            /*
             * SERIES, AND THE KEYS KEPT FOR SATELLITES THAT PREDATE 3.0.0.
             *
             * series_id and series_parent used to be post IDs; a series is a
             * term now and there is no parent. Both keys stay in the payload,
             * carrying the term ID, because a satellite reading them only ever
             * used them to answer "are these two events part of the same
             * thing", and the term ID answers that identically. Dropping the
             * keys would have broken every satellite at once; changing what
             * they mean under the same names would be worse.
             *
             * recurrence_group is the new, separate fact: which events were
             * generated together. See SFAF_Recurrence.
             */
            'series_id'       => SFAF_Series::id_for_event( $post_id ),
            'series_parent'   => SFAF_Series::id_for_event( $post_id ),
            'series_name'     => SFAF_Series::name_for_event( $post_id ),
            'series_image'    => sfaf_series_image_url( SFAF_Series::id_for_event( $post_id ) ),
            'recurrence_group'=> SFAF_Recurrence::group_of( $post_id ),
            'show'            => array(
                'rsvp'      => get_post_meta( $post_id, '_uc_show_rsvp', true ),
                'donate'    => get_post_meta( $post_id, '_uc_show_donate', true ),
                'social'    => get_post_meta( $post_id, '_uc_show_social', true ),
                'calendar'  => get_post_meta( $post_id, '_uc_show_calendar', true ),
                'reminders' => get_post_meta( $post_id, '_uc_show_reminders', true ),
            ),
            'faq'             => sfaf_get_faqs( $post_id ),
            'rsvp_count'      => sfaf_get_rsvp_count( $post_id ),
            // Legacy (names + colour map) kept for older satellites.
            'categories'      => $categories,
            'category_colors' => $cat_colors,
            // An ARRAY of names, which it always was, so a satellite reading two
            // gets two. Ordered, so the same event does not arrive in a
            // different order on two fetches.
            'organizer'       => SFAF_Organizers::names_for_event( $post_id ),
            'venue'           => wp_get_post_terms( $post_id, 'uc_venue', array( 'fields' => 'names' ) ),
            // Full term identity (stable id + slug + colour) so satellites can sync
            // renames, slug changes and colour changes onto their local terms.
            'terms'           => array(
                'uc_event_category' => $this->term_payload( $post_id, 'uc_event_category', true ),
                'uc_organizer'      => $this->term_payload( $post_id, 'uc_organizer', false ),
                'uc_venue'          => $this->term_payload( $post_id, 'uc_venue', false ),
            ),
            'image'           => sfaf_event_image_url( $post_id ),
            'permalink'       => get_permalink( $post_id ),
        );
    }

    /**
     * Term identity for one taxonomy on an event: id, name, slug (+ colour for
     * categories). Lets satellites match terms by a stable id and update name/
     * slug/colour instead of silently creating duplicates on a rename.
     */
    private function term_payload( $post_id, $taxonomy, $with_color ) {
        $terms = wp_get_post_terms( $post_id, $taxonomy );
        $out   = array();
        if ( is_wp_error( $terms ) ) {
            return $out;
        }
        foreach ( $terms as $t ) {
            $row = array(
                'id'   => (int) $t->term_id,
                'name' => $t->name,
                'slug' => $t->slug,
            );
            if ( $with_color ) {
                $row['color'] = get_term_meta( $t->term_id, '_uc_category_color', true );
            }
            $out[] = $row;
        }
        return $out;
    }
}
